---
title: "Data Generation"
author: "Philipp Hellwig"
format:
  revealjs: 
    slide-number: true
    css: styles.css
    width: 2000
jupyter: python3
---

## Progress

- Generated data (train+test splits; only your transformations)
    - Total samples $\approx 170,000$
- Batching
- Forward Pass

## Transformation overview (train & val):

::: {.small-text}
1.	[Extend Sequence (a b c d -> a b c d e)]{style="color:green;"}
2.	[Successor (a b c d -> a b c e)]{style="color:green;"}
3.	[Predecessor (b c d e -> a c d e)]{style="color:green;"}
4.	[Remove Redundant letter (a b b c d -> a b c d)]{style="color:green;"}
5.	[Fix alphabetic sequence (a b c w e -> a b c d e)]{style="color:green;"}
6.	[Sort (a d c b e -> a b c d e)]{style="color:green;"}
7.	Sort + Group (aa dd cc bb ee -> aa bb cc dd ee)
8.	Remove redundant + Interleave (a x b x b x c x d -> a x b x c x d)
9.	Remove Redundant + successor (a b b c d -> a b c e)
10.	Fix alphabetic sequence + extend sequence (a b c w e -> a b c d e)
:::

## Transformation overview (test)

::: {.small-text}
11.	Remove Redundant + Sort (a d d c b e -> a b c d e) 
12.	Extend Sequence + Predecessor (b c d e -> a c d e f)
13.	Fix alphabetic sequence + Interleave (a f b f c f w f e -> a f b f c f d f e)
14.	Extend sequence + Group (aa bb cc dd -> aa bb cc dd ee)
15.	Extend Sequence + Extend Sequence + Successor (a b c d -> a b c d e g)
16.	Fix alphabetic Sequence + Predecessor + Successor (a b c w e -> a a c d f)
17.	Reverse (a b c d -> d c b a)
18.	Shift (a b c d -> e f g h)
19.	Replicate (a b c d -> a b c d a b c d)
:::

## Data
```{python}
import pandas as pd
from itables import show
df = pd.read_csv("data/all_samples.csv")
show(df)
```

## Dataset To Do

- create functions for new transformation rules
- create combinations
- apply transformations at variable positions
- removing samples that also appear in the human data set
- vary the number of examples per query

## Dataset and DataLoader

```{python code-line-numbers=8-9}
#| echo: true
import datasets as dat
from datasets import Lang, LetterStringDataset
import torch
from torch.utils.data import DataLoader

D_train = LetterStringDataset(mode="train", data_dir="data")
train_dataloader = DataLoader(
    D_train,
    batch_size=5,
    collate_fn=lambda x:dat.get_mlc_batch(x,D_train.langs),
    shuffle=True
    )

```

## Example batch
```{python}
#| echo: true
sample_batch = next(iter(train_dataloader))
print("Input to the model:")
print(sample_batch["xq_context"][0])
D_train.pprint(sample_batch)
```

## Questions

- How to optimally load the data? 
    - are batches necessary?

## Setting up MLC model
```{python}
from model import MLC, describe_model
#| echo: false
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

in_size = len(D_train.langs["input"].index2symbol)
out_size = len(D_train.langs["output"].index2symbol)
pad_in = D_train.langs["input"].PAD_idx
pad_out = D_train.langs["output"].PAD_idx
```
```{python}
#| echo: true
net = MLC(
    hidden_size=128, 
    input_size=in_size, 
    output_size=out_size, 
    PAD_idx_input=pad_in, 
    PAD_idx_output=pad_out
    )
net = net.to(device=DEVICE)

describe_model(net)        
```

## Evaluate Batch
- still need to fix output alphabet (includes tokens that shouldn't be part of output)
```{python}
#| echo: true
from evaluate import predict
predictions = predict(
    batch=sample_batch,
    net=net, 
    langs=D_train.langs,
    max_length=20,
    eval_type="sample"
)

for pred in predictions:
    print("".join(pred))      
```


## Next Steps
- implement training loop
- train MLC model 
    - few epochs
    - preliminary data set
- complete data set generation (add missing functions & features)